###############################################################################
# @file ader_weno/Makefile                                                   #
###############################################################################

NAME := ader_weno

OBJS := 
OBJS += ader_weno.o
OBJS += finite_volume.o
OBJS += weno.o

SUBDIRS := 

include $(TOP)/Makefile.subdirs
