###############################################################################
# @file advection/Makefile                                                    #
###############################################################################

NAME := advection

OBJS :=
OBJS += advection.o

SUBDIRS :=

include $(TOP)/Makefile.subdirs
