###############################################################################
# @file grid/Makefile                                                   #
###############################################################################

NAME := grid

OBJS := 
OBJS += grid.o
OBJS += admissibility.o
OBJS += interpolation.o

SUBDIRS := 

include $(TOP)/Makefile.subdirs
