###############################################################################
# @file grhdc/Makefile                                                       #
###############################################################################

NAME := grhdc

OBJS :=
OBJS += grhdc.o
OBJS += hack.o

SUBDIRS :=

include $(TOP)/Makefile.subdirs
