###############################################################################
# @file data/Makefile                                                   #
###############################################################################

NAME := data

OBJS := 
OBJS += data.o
OBJS += alloc.o
OBJS += free.o
OBJS += init.o
OBJS += parameter.o
OBJS += convergence.o
OBJS += timer.o

SUBDIRS := 

include $(TOP)/Makefile.subdirs
